# To set the app's name, for Android edit /android/app/src/main/AndroidManifest.xml - android:label,
# for iOS edit /ios/Runner/info.plist - <key>CFBundleName</key>.
name: modern_art_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.12.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  camera: ^0.8.1
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.0
  flutter_lorem: ^2.0.0
  flutter_markdown: ^0.6.1
  # track master branch of flutter_settings_screens for now, until new version is available, see
  # https://github.com/GAM3RG33K/flutter_settings_screens/issues/34
  flutter_settings_screens:
    git:
      url: https://github.com/GAM3RG33K/flutter_settings_screens
      ref: master
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.3.2
  fluttertoast: ^8.0.3
  google_fonts: ^2.0.0
  #  getwidget: ^1.2.2
  http: ^0.13.0
  moor: ^4.2.1
  moor_db_viewer: ^3.0.0
  palette_generator: ^0.3.0
  path:
  path_provider:
  package_info: ^2.0.0
  photo_view: ^0.11.1
  provider: ^5.0.0
  sensors: ^2.0.0
  sentry_flutter: ^4.0.4
  share: ^2.0.1
  sqlite3_flutter_libs: ^0.4.1
  # adding tflite from Github for now, since the pub version contains a bug for Android
  # versions <= 6.0, see https://github.com/shaqian/flutter_tflite/issues/165, could be reverted
  # once the new version is available officially
  tflite:
    git:
      url: https://github.com/shaqian/flutter_tflite.git
      ref: master
  vibration: ^1.7.3
  url_launcher: ^6.0.3

  # localization related dependencies
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^3.0.0
  intl: ^0.17.0

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.0
  flutter_sheet_localization_generator: ^3.0.0
  flutter_test:
    sdk: flutter
  moor_generator: ^4.2.1
  test: ^1.16.5
  analyzer: ^1.2.0

flutter_icons:
  #  run `flutter pub run flutter_launcher_icons:main` in the terminal to create app launcher icons
  #  image_path_android: "assets/app_launcher_icons/hadjida_untitled_app_icon_android.png"
  image_path: "assets/app_launcher_icons/hadjida_untitled_app_icon_square_ios.png"
  ios: true
  android: false
  # only available for Android 8.0 devices and above
  #  adaptive_icon_background: "#674545"
  #  adaptive_icon_foreground: "assets/app_launcher_icons/hadjida_untitled_app_icon_android_adaptive.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - CHANGELOG.md
    - assets/
    - assets/data/
    - assets/google_fonts/
    - assets/painters/
    - assets/paintings/
    #    - assets/tflite/VGG_with_no_art_quant.tflite
    - assets/tflite/MobNetNoArt500Frames_4.tflite
    #    - assets/tflite/InceptionV3NoArt500Frames_quant.tflite
    - assets/tflite/MobileNet_No_Art_labels.txt
    #    - assets/tflite/
    - assets/app_launcher_icons/hadjida_untitled_app_icon_square_android_adaptive.png
#    - assets/tflite/other/
