# To set the app's name, for Android edit /android/app/src/main/AndroidManifest.xml - android:label,
# for iOS edit /ios/Runner/info.plist - <key>CFBundleName</key>.
name: modern_art_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.12.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  camera: ^0.9.4+5
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.0
  flutter_lorem: ^2.0.0
  flutter_markdown: ^0.6.9
  flutter_settings_screens: ^0.3.2-null-safety
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.4.1
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  http: ^0.13.1
  moor: ^4.6.1+1
  moor_db_viewer: ^5.0.0
  palette_generator: ^0.3.2
  path:
  path_provider:
  package_info: ^2.0.2
  photo_view: ^0.13.0
  provider: ^6.0.1
  sensors: ^2.0.3
#  sentry_flutter: ^6.2.2
  share: ^2.0.4
  sqlite3_flutter_libs: ^0.5.2
  # adding tflite from Github for now, since the pub version contains a bug for Android
  # versions <= 6.0, see https://github.com/shaqian/flutter_tflite/issues/165, could be reverted
  # once the new version is available officially
  tflite:
    git:
      url: https://github.com/shaqian/flutter_tflite.git
      ref: master
  vibration: ^1.7.4-nullsafety.0
  url_launcher: ^6.0.17

  # localization related dependencies
  flutter_localizations:
    sdk: flutter
  flutter_sheet_localization: ^5.1.1
  intl: ^0.17.0

#dependency_overrides:
#  analyzer: ^1.4.0

dev_dependencies:
  analyzer: ^2.1.0
  build_runner: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_sheet_localization_generator:
    git:
      url: https://github.com/msthoma/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator
      ref: master
  flutter_test:
    sdk: flutter
  moor_generator: ^4.6.0+1
  #  test: ^1.20.0
  # temporarily necessary to fix the issue below, try removing in the future
  # https://github.com/simolus3/moor/issues/553
  # https://github.com/simolus3/moor/issues/777

flutter_icons:
  #  run `flutter pub run flutter_launcher_icons:main` in the terminal to create app launcher icons
  #  image_path_android: "assets/app_launcher_icons/hadjida_untitled_app_icon_android.png"
  image_path: "assets/app_launcher_icons/hadjida_untitled_app_icon_square_ios.png"
  ios: true
  android: false
  # only available for Android 8.0 devices and above
  #  adaptive_icon_background: "#674545"
  #  adaptive_icon_foreground: "assets/app_launcher_icons/hadjida_untitled_app_icon_android_adaptive.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - CHANGELOG.md
    - assets/
    - assets/data/
    - assets/google_fonts/
    - assets/painters/
    - assets/paintings/
    - assets/tflite/MobNetNoArt500Frames_4.tflite
    - assets/tflite/MobileNet_No_Art_labels.txt
    - assets/app_launcher_icons/hadjida_untitled_app_icon_square_android_adaptive.png
