import 'package:flutter/material.dart';

import 'lang/localization.dart';

extension Localization on BuildContext {
  /// Extension method on [BuildContext] that provides access to the localized
  /// list of strings generated by the flutter_sheet_localization library.
  AppLocalizations_Labels strings() => AppLocalizations.of(this);
}
